//事务类型定义

#pragma once

enum TransactionType
{
	// 邮件相关事务定义
	TRAN_TYPE_MAIL_ASSET		= 1001,
	TRAN_TYPE_GET_ITEM_AFFIX	= 1002,
	TRAN_TYPE_GET_CASH_AFFIX	= 1003,
	TRAN_TYPE_WRITE_MAIL		= 1004,
	TRAN_TYPE_PAYFORMAIL		= 1005,	

	// 拍卖系统
	TRAN_TYPE_AUCTION_SELL_TRAN	= 1020,
	TRAN_TYPE_AUCTION_BUY_TRAN	= 1021,

	// 门派
	TRAN_TYPE_CREATE_GUILD		= 1030,
	TRAN_TYPE_DONATE_MATERIALS  = 1031,

	// 苍穹战场系统
	TRAN_TYPE_SKY_ARENA	= 1040,

	TRAN_TYPE_GM				= 2001,
};
