#include "LM_LocaleManager.h"
/********************************************************************
	created:	2013/07/24
	filename: 	ClientTextDefine.h
	file path:	Src
	file base:	ClientTextDefine
	file ext:	h
	author:		cjg
	
	purpose:	
*********************************************************************/

#ifndef _CLIENT_TEXT_DEFINE_H
#define _CLIENT_TEXT_DEFINE_H 

#define CLIENT_TEXT_YEAR GET_MSG(LC_HELPER_CPP_008)
#define CLIENT_TEXT_MONTH GET_MSG(CLIENTTEXTDEFINE_H_001)
#define CLIENT_TEXT_DAY GET_MSG(GUILDCOMMDEF_H_025)
#define CLIENT_TEXT_WEEK GET_MSG(CLIENTTEXTDEFINE_H_002)
#define CLIENT_TEXT_GUILD_WAR_TITLE	GET_MSG(CLIENTTEXTDEFINE_H_003)
#define CLIENT_TEXT_GUILD_WAR_GUILD_TITLE	GET_MSG(CLIENTTEXTDEFINE_H_004)
#define CLIENT_TEXT_GLOBAL_GUILD_WAR_TITLE	GET_MSG(CLIENTTEXTDEFINE_H_005)
#define CLIENT_TEXT_GLOBAL_GUILD_WAR_GUILD_TITLE	GET_MSG(CLIENTTEXTDEFINE_H_006)

//common string
#define		CTSTR_UNKNOWN					GET_MSG(LC_CLIENTSOCIETYASSET_CPP_001)
#define		CTSTR_YOU						GET_MSG(CLIENTTEXTDEFINE_H_007)
#define		CTSTR_YOU2						GET_MSG(LC_CLIENTGAMEPLAYER_CPP_006)
#define		CTSTR_YOU3						GET_MSG(LC_CLIENTGAMEPLAYER_CPP_008)
#define		CTSTR_SKILL						GET_MSG(CLIENTTEXTDEFINE_H_008)

//nouns
#define		CTSTR_SKILLPOINT				GET_MSG(CLIENTTEXTDEFINE_H_009)
#define		CTSTR_GOLD						GET_MSG(LC_GUILDSTRUCT_CPP_010)
#define		CTSTR_COUNT_GOLD				GET_MSG(CLIENTTEXTDEFINE_H_010)
#define		CTSTR_UNKNOWN_PLAYER			GET_MSG(CLIENTTEXTDEFINE_H_011)
#define		CTSTR_ITEM						GET_MSG(CLIENTTEXTDEFINE_H_012)
#define		CTSTR_LEVEL						GET_MSG(CLIENTTEXTDEFINE_H_013)
#define		CTSTR_RT_UNBINDYUANBAO			GET_MSG(CLIENTDEFINE_H_014)
#define		CTSTR_SOULPOINT					GET_MSG(CLIENTTEXTDEFINE_H_017)
#define		CTSTR_RUNECREAM					GET_MSG(CLIENTTEXTDEFINE_H_019)

//damage type string
#define		DAMAGE_TYPE_UNKNOWN				GET_MSG(LC_CLIENTSOCIETYASSET_CPP_001)
#define		DAMAGE_TYPE_NORMAL				GET_MSG(LC_HELPER_CPP_012)
#define		DAMAGE_TYPE_SKILL				GET_MSG(UT_GAMESERVERLOGMANAGER_CPP_001)
#define		DAMAGE_TYPE_DOT					"DOT"
#define		DAMAGE_TYPE_REBOUND				GET_MSG(CLIENTTEXTDEFINE_H_014)
#define		DAMAGE_TYPE_SHARE				GET_MSG(CLIENTTEXTDEFINE_H_015)

#define		CTSTR_BELONG_GUILD				GET_MSG(CLIENTTEXTDEFINE_H_016)

#endif	//_CLIENT_TEXT_DEFINE_H
